//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommitteeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendum
    {
        public int id { get; set; }
        public string AgendaTime { get; set; }
        public string AgendaDesc { get; set; }
        public int MeetingId { get; set; }
        public string CreatedAt { get; set; }
        public string UpdatedAt { get; set; }
    }
}
