//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommitteeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteesMember
    {
        public int CommitteeMemberId { get; set; }
        public Nullable<int> CommitteeId { get; set; }
        public int MemberId { get; set; }
        public string CommitteeDate { get; set; }
        public Nullable<bool> MemberWillAttend { get; set; }
        public Nullable<bool> AcceptProceedings { get; set; }
        public string ReasonOfRejection { get; set; }
        public string AgendamodifingSuggession { get; set; }
        public string AlertTime { get; set; }
        public string MeetingTitle { get; set; }
        public string MeetingAddress { get; set; }
        public string MeetingStatus { get; set; }
        public string AgendaTime { get; set; }
        public string AgendaDescription { get; set; }
        public string MeetingDate { get; set; }
        public Nullable<int> MeetingId { get; set; }
        public Nullable<bool> IsMemberAcceptedMiutesOfCommittee { get; set; }
        public string MemberSignature { get; set; }
        public Nullable<int> AlertId { get; set; }
        public string CreatedAt { get; set; }
        public string UpdatedAt { get; set; }
        public Nullable<int> CommitteeRole { get; set; }
        public Nullable<bool> IsMinuteAccepted { get; set; }
    
        public virtual Committee Committee { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual Meeting Meeting { get; set; }
        public virtual SystemRole SystemRole { get; set; }
    }
}
