//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommitteeApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Committee_DBEntities1 : DbContext
    {
        public Committee_DBEntities1()
            : base("name=Committee_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<Committee> Committees { get; set; }
        public virtual DbSet<CommitteesMember> CommitteesMembers { get; set; }
        public virtual DbSet<CoommitteLookup> CoommitteLookups { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Agendum> Agenda { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Importance> Importances { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<MeetingHistory> MeetingHistories { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<SystemRole> SystemRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<MobileVerification> MobileVerifications { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<ValidCode> ValidCodes { get; set; }
        public virtual DbSet<ClickAction> ClickActions { get; set; }
        public virtual DbSet<MeetingImage> MeetingImages { get; set; }
    }
}
