//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommitteeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.Agenda = new HashSet<Agendum>();
            this.MeetingHistories = new HashSet<MeetingHistory>();
            this.CommitteesMembers = new HashSet<CommitteesMember>();
        }
    
        public int MeetingId { get; set; }
        public string MeetingTitle { get; set; }
        public Nullable<int> CommitteeId { get; set; }
        public string MeetingDate { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string MeetingDesc { get; set; }
        public Nullable<int> Status { get; set; }
        public string proceedings { get; set; }
        public string MeetingAddress { get; set; }
        public string AgendaTime { get; set; }
        public string AgendaDescription { get; set; }
        public string MinutesOfMeeting { get; set; }
        public string MeetingTime { get; set; }
        public Nullable<int> MeetingHistory { get; set; }
        public string CreatedAt { get; set; }
        public string UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendum> Agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingHistory> MeetingHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommitteesMember> CommitteesMembers { get; set; }
    }
}
