//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommitteeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Alerts = new HashSet<Alert>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string Title { get; set; }
        public Nullable<int> UserRole { get; set; }
        public string UserPassword { get; set; }
        public string UserEmailId { get; set; }
        public string UserImage { get; set; }
        public Nullable<int> SystemRole { get; set; }
        public string WorkSide { get; set; }
        public Nullable<int> ManagerOfDepartment { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string FCMToken { get; set; }
        public string DeviceType { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual SystemRole SystemRoleMap { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alert> Alerts { get; set; }
    }
}
